PREPROCESS_CONSTANT:
    NUMBER_PATTERN: '[0-9]'
    TEXT_PATTERN: '[a-zA-Z]'
    WORD_PATTERN: '[\w+]'
    SPECIAL_CHAR_PATTERN: '[!@#$%^&*(),?":;{}\''|<>~`=_\\/+-]'
    RANGE_PATTERN: '(\d+)\s*[-|to]+\s*(\d+)'
    URL_PATTERN: 'http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\(\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+'


THRESHOLD:
    CORPUS_WORD_LIMIT: 3
    PARTITION_SIZE: 100
    DATE_MIN_YEAR: 1800
    DATE_MAX_YEAR: 2100
    SYMSPELL_PREFIX_LEN: 7
    SYMSPELL_EDIT_DIST: 0
    SYMSPELL_TERM_INDEX: 0
    SYMSPELL_COUNT_INDEX: 1
    DATA_VALUES_LIMIT: 1000000
    XGB_MODEL_WEIGHT: 0.4
    RF_MODEL_WEIGHT: 0.3
    SVM_MODEL_WEIGHT: 0.3

L3PARAMS:
    SAMPLE_SIZE: 100
    DF_SAMPLE_SIZE: 10

FILE_TYPE:
    FILE_ENCODING: 'iso-8859-1'
    DTYPE_ENCODING: 'unicode'
